# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Logmonster
version:      3.04
version_from: logmonster.pl
installdirs:  site
requires:
    Compress::Zlib:                2
    Date::Parse:                   2
    Params::Validate:              0.8
    Regexp::Log:                   0.04

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
